CREATE TABLE IF NOT EXISTS "Url" (
    id SERIAL PRIMARY KEY,
    longUrl TEXT UNIQUE NOT NULL,
    shortCode VARCHAR(255) UNIQUE NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_url_longurl ON "Url"(longUrl);
CREATE INDEX IF NOT EXISTS idx_url_shortcode ON "Url"(shortCode);
